Adjust build test

diff --git a/.github/workflows/build-php-images.yml b/.github/workflows/build-php-images.yml
--- a/.github/workflows/build-php-images.yml
+++ b/.github/workflows/build-php-images.yml
@@ -14,6 +14,12 @@ jobs:
       TERM: xterm
     strategy:
       matrix:
+        lando-versions:
+          - edge
+        os:
+          - ubuntu-20.04
+        node-version:
+          - '14'
         include:
           - image: php
             tag: 8.1-fpm-4
@@ -56,18 +62,61 @@ jobs:
         id: pr
         if: ${{ github.event_name == 'pull_request' }}
         run: echo "::set-output name=TAG_SUFFIX::-edge"
-      - name: Login to DockerHub
-        uses: docker/login-action@v1
+      # - name: Login to DockerHub
+      #   uses: docker/login-action@v1
+      #   with:
+      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
+      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
+      # - name: Build and push devwithlando/${{ matrix.image }}:${{ matrix.tag }}${{ steps.pr.outputs.TAG_SUFFIX }}
+      #   uses: docker/build-push-action@v2
+      #   with:
+      #     context: ${{ matrix.context }}
+      #     platforms: linux/amd64,linux/arm64
+      #     push: true
+      #     tags: devwithlando/${{ matrix.image }}:${{ matrix.tag }}${{ steps.pr.outputs.TAG_SUFFIX }}
+
+      # Handle Lando Install to test the images after build
+      - name: Install node ${{ matrix.node-version }}
+        uses: actions/setup-node@v2
         with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-      - name: Build and push devwithlando/${{ matrix.image }}:${{ matrix.tag }}${{ steps.pr.outputs.TAG_SUFFIX }}
-        uses: docker/build-push-action@v2
+          node-version: ${{ matrix.node-version }}
+      - name: Get Yarn cache directory
+        id: yarn-cache-dir-path
+        run: echo "::set-output name=dir::$(yarn cache dir)"
+      - name: Use Yarn cache
+        uses: actions/cache@v2
+        id: yarn-cache
         with:
-          context: ${{ matrix.context }}
-          platforms: linux/amd64,linux/arm64
-          push: true
-          tags: devwithlando/${{ matrix.image }}:${{ matrix.tag }}${{ steps.pr.outputs.TAG_SUFFIX }}
+          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
+          key: ${{ runner.os }}-yarn-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
+      - name: Install Yarn dependencies
+        run: yarn install --prefer-offline --frozen-lockfile
+      - name: Grab latest edge Lando CLI
+        run: |
+          sudo curl -fsSL -o /usr/local/bin/lando "https://files.lando.dev/cli/lando-linux-x64-${{ matrix.lando-versions }}"
+          sudo chmod +x /usr/local/bin/lando
+      - name: Move in lando config appropriate for testing
+        run: |
+          mkdir -p ~/.lando/cache
+          cp -f actions-lando-config.yml ~/.lando/config.yml
+          echo false > ~/.lando/cache/report_errors
+          lando --clear
+      - name: Verify Lando works and we are dogfooding this plugin for tests
+        run: |
+          lando version
+          lando config --path plugins | grep php | grep /home/runner/work/php/php || echo "::error:: Not dogfooding this plugin correctly! "
+      # This block should eventually become use lando/actions-leia@v2
+      # @NOTE? Do we want a way for our leia-action to configure apparmor since
+      # this might break a whole bunch of tests? or is this literally just a thing
+      # for the Lagoon mysql/mariadb container?
+      - name: Configure apparmor
+        run: |
+          set -x
+          sudo apt-get remove mysql-server --purge
+          sudo apt-get install apparmor-profiles
+          sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
+
+
       - name: Test Edge Images on PR
         if: ${{ github.event_name == 'pull_request' }}
         shell: bash
