Adjust php test

diff --git a/.github/workflows/pr-php-tests.yml b/.github/workflows/pr-php-tests.yml
--- a/.github/workflows/pr-php-tests.yml
+++ b/.github/workflows/pr-php-tests.yml
@@ -45,23 +45,31 @@ jobs:
         run: |
           docker --version | grep "20.10."
           docker-compose --version | grep "1.29."
-      # - name: Install via hyperdrive if above is bad
-      - name: Disable usage and error reporting
+      - name: Grab latest edge Lando CLI
+        run: |
+          sudo curl -fsSL -o /usr/local/bin/lando "https://files.lando.dev/cli/lando-linux-x64-${{ matrix.lando-versions }}"
+          sudo chmod +x /usr/local/bin/lando
+      - name: Move in lando config appropriate for testing
         run: |
           mkdir -p ~/.lando/cache
+          cp -f actions-lando-config.yml ~/.lando/config.yml
           echo false > ~/.lando/cache/report_errors
-          sed -i "s/report: true.*/report: false/" config.yml
-      - name: Package CLI
-        run: yarn build:cli
-      - name: Replace source CLI with packaged one
-        run: sudo mv ./dist/@lando/cli /usr/local/bin/lando
-      - name: Verify we can run the packaged CLI
+          lando --clear
+      - name: Verify Lando works and we are dogfooding this plugin for tests
         run: |
           lando version
-          lando config
+          lando config --path plugins | grep php | grep /home/runner/work/php/php || echo "::error:: Not dogfooding this plugin correctly! "
 
       # This block should eventually become use lando/actions-leia@v2
-      - name: Generate tests
-        run: yarn generate:tests
-      - name: Run ${{ matrix.leia-tests }} tests
-        run: yarn mocha --timeout 900000 ./test/${{ matrix.leia-tests }}.func.js
+      # @NOTE? Do we want a way for our leia-action to configure apparmor since
+      # this might break a whole bunch of tests? or is this literally just a thing
+      # for the Lagoon mysql/mariadb container?
+      - name: Configure apparmor
+        run: |
+          set -x
+          sudo apt-get remove mysql-server --purge
+          sudo apt-get install apparmor-profiles
+          sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
+      - name: Run leia tests
+        shell: bash
+        run: yarn leia "./${{ matrix.leia-tests }}/README.md" -c 'Destroy tests' --stdin --shell bash
